### ISSUE TITLE
Reverse the action of time input icon buttons

### ISSUE THREAD

**Issue by Harsh8833** [DSCVITBHOPAL/Timer#15]
The time should increase on clicking the down arrow.

**Comment by rishuyadav** [comment]
Hey @Harsh8833 can you please elaborate on this issue ?  I am unable to understand what exactly is required and why

**Comment by Harsh8833** [comment]
![image](https://user-images.githubusercontent.com/90051370/198148262-49843e9d-2162-4b3e-bd76-d4f61fb9e5b7.png)
You have to reverse the onTap of these arrow icons so that on clicking the down arrow time should increase and on clicking the up arrow time should decrease.

**Comment by rishuyadav** [comment]
Hey @Harsh8833 do you mind adding hacktoberfest-accepted tag pls
