### ISSUE TITLE
Reset button while timer is running

### ISSUE THREAD

**Issue by Apoorva57** [DSCVITBHOPAL/Timer#17]
Create a reset button next to the pause button while the timer is running, to restart the timer from the beginning.

**Comment by yaviral17** [comment]
is this issue still open  ?

**Comment by SuyogMahajan** [comment]
Hey I want to work on this one 🥸

**Comment by Apoorva57** [comment]
hi @SuyogMahajan , you can start working on this one and create a pull request, we will merge it after reviewing
