### ISSUE TITLE
Animation Color Change

### ISSUE THREAD

**Issue by Vishesht27** [DSCVITBHOPAL/Timer#3]
Change the color of the animation of the arc in the application as time passes

**Comment by mukulasija** [comment]
I would like to work on this

**Comment by Nayan2701** [comment]
I want to contribute . So please assign this issue to me

**Comment by Nayan2701** [comment]
Nayan21BCE10163
i want to contribute.So please assign me this issue

**Comment by Vishesht27** [comment]
You have been assigned , go for it
