### ISSUE TITLE
Add Splash Screen for less than Android 12 version

### ISSUE THREAD

**Issue by Vishesht27** [DSCVITBHOPAL/Timer#4]
Create a splash screen for this app in which you will show the logo of the app and then it will be redirected to the main screen.

**Comment by KaranSinghBisht** [comment]
Hey! I would like to work on making the splash screen

**Comment by Vishesht27** [comment]
You can start working on it and give it a pr, we will review for sure

**Comment by KaranSinghBisht** [comment]
Which one should I pr? Any changes required?
![Splash1](https://user-images.githubusercontent.com/69008866/135739608-50ae211a-7e09-4db4-82d3-2bcea033f4c1.png)
![Splash2](https://user-images.githubusercontent.com/69008866/135739609-1fdefeb7-ba81-42f6-b7fd-2147145cd5d4.png)

**Comment by Apoorva57** [comment]
the issue is still open for all to work on, make sure it's for the android version lower than android12.

**Comment by yaviral17** [comment]
I can do that if the issue is still open

**Comment by hey-sameer** [comment]
I would like to work on this issue @Vishesht27 . Can you please assign me this?
