### ISSUE TITLE
Taking User Input

### ISSUE THREAD

**Issue by Vishesht27** [DSCVITBHOPAL/Timer#5]
Taking the input from user and removing the static data , so that application timer works according to the user's input

**Comment by Kardelio** [comment]
Hey can i ask a question, when you say user input, do you mean that the user can enter how long the timer should run for? At the moment It looks like its hard coded to be 100 seconds right? so would this issue be to make that dynamic and depend on the user?

If so then i would love to grab hold of this issue and give it a go if thats ok?

**Comment by Vishesht27** [comment]
Yes , you are right

**Comment by Kardelio** [comment]
@Vishesht27 would you mind if I had a crack at this issue then?

**Comment by Vishesht27** [comment]
Yes , sure

**Comment by Kardelio** [comment]
@Vishesht27 awesome! Thank you ill get on it this evening! Would you mind assigning me to this issue?

**Comment by Kardelio** [comment]
@Vishesht27 ACTUALLY, thank you but I have decided that I will not pick up this issue, sorry about the confusion and if i have temporarily caused any delays. My apologies and thank you for your time!

**Comment by Kunal-Attri** [comment]
@Vishesht27 May I work on this issue?
Also, you just want that to be dynamic.
So, currently the slider goes from 0 to 100.
If i consider 2 cases:
One being the user inputs a value 0 <= t <= 100, then what i am considering is keeping the slider as it is from 0 to 100 scale and position irt according to user input.
Second is when user inputs a value t > 100, then I would increse the slider range and position it to full. 
Am I right?
